#!/bin/bash
# Generate superpod/superpod.env by interactively asking for
# account/partition/group/user. This is a one-time setup step; once the env
# file exists, all other scripts read from it directly at submit/runtime.
#
# Usage:
#   bash superpod/configure_superpod.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/superpod.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "Found existing ${ENV_FILE}. Overwrite? [y/N]"
    read -r answer
    if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
        echo "Aborting. Existing config kept."
        exit 0
    fi
fi

echo "=== SuperPOD configuration ==="
echo "Find your account/partition with: sacctmgr show user \$USER withassoc"
read -rp "SLURM account (e.g. cse): " ACCOUNT
read -rp "GPU partition (default: normal): " PARTITION_GPU
PARTITION_GPU=${PARTITION_GPU:-normal}
read -rp "CPU partition (default: cpu): " PARTITION_CPU
PARTITION_CPU=${PARTITION_CPU:-cpu}
read -rp "Project group name (e.g. cse): " GROUP
read -rp "Your HKUST username (no @ust.hk): " USER
read -rp "CPU cores per GPU job (default: 28): " CPUS_PER_TASK
CPUS_PER_TASK=${CPUS_PER_TASK:-28}
read -rp "CPU cores per CPU job (default: 8): " CPUS_PER_TASK_CPU
CPUS_PER_TASK_CPU=${CPUS_PER_TASK_CPU:-8}

cat > "$ENV_FILE" <<EOF
# SuperPOD environment configuration.
# Generated by configure_superpod.sh on $(date -Iseconds)

SUPERPOD_ACCOUNT=${ACCOUNT}
SUPERPOD_PARTITION_GPU=${PARTITION_GPU}
SUPERPOD_PARTITION_CPU=${PARTITION_CPU}
SUPERPOD_GROUP=${GROUP}
SUPERPOD_USER=${USER}

PROJECT_DIR=/project/\${SUPERPOD_GROUP}/lewm-plus
CONTAINER_PATH=\$HOME/containers/lewm.sqsh

CPUS_PER_TASK=${CPUS_PER_TASK}
CPUS_PER_TASK_CPU=${CPUS_PER_TASK_CPU}

STABLEWM_HOME=\${PROJECT_DIR}/.stable-wm
SCRATCH_DATA=/scratch/\${SUPERPOD_GROUP}/datasets
EOF

echo ""
echo "Wrote ${ENV_FILE}"
echo "You can now submit jobs directly, e.g.:"
echo "  bash superpod/hello_superpod.sh"
echo "  bash superpod/hello_superpod_gpu.sh"
echo "  bash superpod/train_lewm.sh data=pusht_h5 trainer.max_epochs=100"
