#!/bin/bash
# Generate superpod.env by interactively asking for account/group/user,
# then substitute Slurm placeholders in all SuperPOD batch scripts.
#
# Usage:
#   bash docs/scripts/superpod/configure_superpod.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/superpod.env"

echo "=== SuperPOD configuration ==="
echo "Find your account/partition with: sacctmgr show user \$USER withassoc"
read -rp "SLURM account (e.g. cse): " ACCOUNT
read -rp "GPU partition (default: normal): " PARTITION_GPU
PARTITION_GPU=${PARTITION_GPU:-normal}
read -rp "CPU partition (default: cpu): " PARTITION_CPU
PARTITION_CPU=${PARTITION_CPU:-cpu}
read -rp "Project group name (e.g. cse): " GROUP
read -rp "Your HKUST username (no @ust.hk): " USER
read -rp "CPU cores per GPU job (default: 28): " CPUS_PER_TASK
CPUS_PER_TASK=${CPUS_PER_TASK:-28}
read -rp "CPU cores per CPU job (default: 8): " CPUS_PER_TASK_CPU
CPUS_PER_TASK_CPU=${CPUS_PER_TASK_CPU:-8}

cat > "$ENV_FILE" <<EOF
# SuperPOD environment configuration.
# Generated by configure_superpod.sh on $(date -Iseconds)

SUPERPOD_ACCOUNT=${ACCOUNT}
SUPERPOD_PARTITION_GPU=${PARTITION_GPU}
SUPERPOD_PARTITION_CPU=${PARTITION_CPU}
SUPERPOD_GROUP=${GROUP}
SUPERPOD_USER=${USER}

PROJECT_DIR=/project/\${SUPERPOD_GROUP}/lewm-plus
CONTAINER_PATH=\$HOME/containers/lewm.sqsh

CPUS_PER_TASK=${CPUS_PER_TASK}
CPUS_PER_TASK_CPU=${CPUS_PER_TASK_CPU}

STABLEWM_HOME=\${PROJECT_DIR}/.stable-wm
SCRATCH_DATA=/scratch/\${SUPERPOD_GROUP}/datasets
EOF

echo ""
echo "Wrote ${ENV_FILE}"

# Substitute Slurm placeholders in batch scripts. Non-batch scripts
# (interactive_gpu.sh, sync_to_superpod.sh) read superpod.env at runtime.
for f in "$SCRIPT_DIR"/*.sh; do
    case "$(basename "$f")" in
        _common.sh|configure_superpod.sh|interactive_gpu.sh|sync_to_superpod.sh)
            continue
            ;;
    esac

    # Only touch scripts that still have Slurm placeholders.
    grep -q '{{ACCOUNT}}\|{{PARTITION_GPU}}\|{{PARTITION_CPU}}' "$f" || continue

    sed -i \
        -e "s/{{ACCOUNT}}/${ACCOUNT}/g" \
        -e "s/{{PARTITION_GPU}}/${PARTITION_GPU}/g" \
        -e "s/{{PARTITION_CPU}}/${PARTITION_CPU}/g" \
        "$f"
    echo "Configured Slurm placeholders in: $f"
done

echo ""
echo "Done. Review superpod.env, then submit jobs with:"
echo "  sbatch docs/scripts/superpod/train_lewm.sh data=pusht_h5 ..."
