defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/ReacherCustom-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: 100
  task: reach

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action

seed: 42
policy: random

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5

eval:
  num_eval: 50
  goal_offset_steps: 25
  eval_budget: 50
  img_size: 224
  dataset_name: reacher_reach_eval
  callables:
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel
    - method: set_target_qpos
      args:
        target_qpos:
          value: goal_qpos

output:
  filename: reacher_reach_results.txt
